### ISSUE TITLE
Enhancement: Unlock blocek Submit buttons, while transaction is ongoing

### ISSUE THREAD

**Issue by DuriSK** [galacticcouncil/Basilisk-mining-ui#154]
If user send transaction, and transaction is ongoing
User should be able to sign and send new transaction, therefore sign button should be unblocked

Current state:
Button for signing transaction is blocked
![image](https://user-images.githubusercontent.com/97346452/200574088-f9b5883f-c7b2-4558-93fc-2a2c6d312173.png)

This task is connected to https://github.com/galacticcouncil/Basilisk-mining-ui/issues/123
User is able to minimise transaction notification, but action button is blocked, so user can not perform any new actions in meantime

**Comment by jak-pan** [comment]
I'd propose to minimize the tx to toast after the tx is in "broadcast" state
