### ISSUE TITLE
Share of the pool calculation

### ISSUE THREAD

**Issue by DuriSK** [galacticcouncil/Basilisk-mining-ui#160]
As user, when im providing liquidity
I want to see % share of the pool, for the share tokens which i would for providing liquidity.

<img width="1063" alt="Screenshot 2022-11-08 at 11 01 30" src="https://user-images.githubusercontent.com/97346452/200840626-00d4ea43-0593-4031-afa9-d184c9a6eb29.png">

Example:
User will get 25 share tokens for providing liquidity
Total issuance of share token is 100 tokens
That means he will own 25% of share tokens

Current state:
Currently we are displaying  how much of the pool user owns totally also with new tokens (as we have 1 user there is 100%...)

**Comment by dqbd** [comment]
Should be fixed in latest build @DuriSK
