### ISSUE TITLE
Wallet disconnected in wallet screen blocks UI

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/Basilisk-mining-ui#174]
We should be able to interact with the app instead of blocking it like here:
This is also the case for Hydra wallet

https://www.figma.com/file/HZt2Xm6sfGWsI3vnnnaMC9/%F0%9F%96%A5--Basilisk-v0.5-%7C-Desktop?node-id=10610%3A171353&t=aiylFEPOyrWHwxSw-4

**Comment by dqbd** [comment]
Replicable only on Safari 16.1 (18614.2.9.1.12)
