### ISSUE TITLE
Give user ability to setup Trade Limit value on Add liquidity and remove liquidity modal windows

### ISSUE THREAD

**Issue by DuriSK** [galacticcouncil/Basilisk-mining-ui#176]
Given user is on add liquidity or remove liquidity screen
They should see their trade limit dislayed
By default this value should be 3%
And if they will click on "Edit"
Than modal window should be opened
And user should be able to specify different trade limit

Note:
This setting should be synchronised between trade screen and add/remove liquidity screen

Design:
https://www.figma.com/file/HZt2Xm6sfGWsI3vnnnaMC9/%F0%9F%96%A5--Basilisk-v0.5-%7C-Desktop?node-id=11684%3A157571&t=S6ZYnNIkZ7NVb4SH-4

**Comment by jak-pan** [comment]
> Given user is on add liquidity or remove liquidity screen They should see their trade limit dislayed By default this value should be 3% And if they will click on "Edit" Than modal window should be opened And user should be able to specify different trade limit
> 
> Note: This setting should be synchronised between trade screen and add/remove liquidity screen
> 
> Design: https://www.figma.com/file/HZt2Xm6sfGWsI3vnnnaMC9/%F0%9F%96%A5--Basilisk-v0.5-%7C-Desktop?node-id=11684%3A157571&t=S6ZYnNIkZ7NVb4SH-4

This setting should not be synchronized

**Comment by DuriSK** [comment]
Will be replaced with new ticket
