### ISSUE TITLE
Incorrect details for farming positions

### ISSUE THREAD

**Issue by dqbd** [galacticcouncil/Basilisk-mining-ui#206]
Date entered position and locked shares are incorrect

Entered date - how is this calculated? I entered the farm in November

![image](https://user-images.githubusercontent.com/1443449/204271425-50bb845d-4060-48b4-9253-b1669bbcedaa.png)

Locked shares are incorrect (@Juraj Ferenc has already raised this issue)

**Comment by obsivac-cleevio** [comment]
Locked shares used to be valued shares, now replaced with deposit shares
