### ISSUE TITLE
Farm Detail Modal - formatting (2 issues)

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/Basilisk-mining-ui#224]
1 ) The "Reward APR %" on the Y-axis of the Loyalty Rewards graph are currently showing the loyalty reward % (which the user does not understand) - this should in fact be the loyalty reward % * APR %

As an example, this pool gives 40.02% APR - this is at 100% loyalty factor, so the Y-axis of this graph should actually start at 50% of the APR (in this case ~20%) and trend up towards max 40.02% APR

<img width="699" alt="image" src="https://user-images.githubusercontent.com/97540577/206440929-bdcb5382-0f8a-4cf4-9a61-be2a4f2da16d.png">

-------

2) Most farms are likely to have a very large number of periods, therefore we should either reformat these numbers so that they do not overlap (this is messy) **or** we should convert this to days using relay chain blocks (this is likely more useful for the user)

**Comment by jak-pan** [comment]
We should probably change this to estimated time instead of periods
