### ISSUE TITLE
Claimable amount is not consistant on different places

### ISSUE THREAD

**Issue by DuriSK** [galacticcouncil/Basilisk-mining-ui#248]
### Expected state:
On pool footer, user should see total $ value of claimable tokens for all positions in that pool

On detail of the farming position, user should see Claimable amout for that position(from all farms for given position)

<img width="1390" alt="FarmClaim" src="https://user-images.githubusercontent.com/97346452/212465480-7724356c-0f79-4b9d-89d1-c99263975e3d.png">

Things to consider when calculating claimable amount for single position:

- is user just in one farm with specific position or in multiple farms?
- is rewards currency the same, or is different for farms?
- how many periods elapsed, since when is user in given farm with this position?
- did user claim before?
- is there loyalty factor for this farm?

### Current State:
Claimable amount, which is displayed at the bottom of the pool
<img width="899" alt="Screenshot 2023-01-13 at 21 45 54" src="https://user-images.githubusercontent.com/97346452/212420139-59f05e32-d32c-4df2-acb9-787674b6be56.png">

is not consistant with number of claimable rewards, which are displayed in the details of the positions(in this case user has two positions in farm)

<img width="496" alt="Screenshot 2023-01-13 at 21 46 29" src="https://user-images.githubusercontent.com/97346452/212420666-8f3b94b9-8dc4-4d19-8d2a-9c072cfe161e.png">

<img width="494" alt="Screenshot 2023-01-13 at 22 15 05" src="https://user-images.githubusercontent.com/97346452/212420689-115d8402-b41f-4423-81bb-c794f0171822.png">

**Comment by dqbd** [comment]
Looking at the code preemptively, it doesn't seem like the issue is significant due to the way how $0.00 USD is rounded. It might be possible, that the addition of two small USD values would cause the discrepancy between $0.01 and $0.02 USD.

@DuriSK Does this issue occur for larger claimable amounts?

**Comment by dqbd** [comment]
Relevant fix for rounding #258
