### ISSUE TITLE
ADD LIQUIDITY from wallet page not functioning correctly

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/Basilisk-mining-ui#286]
2 issues I have identified here:

1. TNKR asset in wallet doesn't have `ADD LIQUIDITY` option, despite there being an active TNKR<>BSX pool
![image](https://user-images.githubusercontent.com/97540577/216560111-35bf86c6-3e64-4f3c-ab43-6dc3b4cea116.png)

2. Probably most easily explained with the video - I am not sure what the logic is here when I select `ADD LIQUIDITY`, on the following modal I'm not really sure how an option becomes selectable or not - I should be able to add liquidity for any 2 assets.

https://user-images.githubusercontent.com/97540577/216560386-cf9f5173-248b-4887-9893-70713644e600.mov

**Comment by DuriSK** [comment]
https://www.notion.so/Add-liquidity-f9ad683858a04255b610ed31c405c317
