### ISSUE TITLE
Active account icons

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/Basilisk-mining-ui#77]
Depending on the wallet at hand and the chain selected we should show identicon. 

polkadot.js should be able to provide you the type of the identicon as it has this data here 
https://github.com/polkadot-js/extension/blob/8e9b87123d0c87ff6b04f4143cd26d472452dd2b/packages/extension-chains/src/bundle.ts#L50

By default talisman shows different custom icon for this generated from public key instead of ss58 address that is blocked on this so I would just show basilisk in that case for now
https://github.com/galacticcouncil/Basilisk-ui/issues/955

**Comment by dqbd** [comment]
As far as we know, it is not possible to obtain the `icon` used for accounts, these are mostly hardcoded in these places:

https://github.com/paritytech/ss58-registry/blob/main/ss58-registry.json
https://github.com/polkadot-js/common/blob/master/packages/networks/src/defaults/icons.ts

Judging by the https://github.com/galacticcouncil/Basilisk-ui/issues/955, the core issue seems to be to match the avatar as seen in the Talisman/Polkadot.js interface, which should be done in the #87 PR.

<img width="465" alt="image" src="https://user-images.githubusercontent.com/1443449/193102916-13230fc9-783b-4b25-9936-c844c9a977f1.png">

**Comment by jak-pan** [comment]
Ok I have been digging heavily and the option to get icon style vanished looks like as part of some upgrade... What we can do instead is that if we show default in-extension address underneath our ss58 we can use classic identicon instead of the one we use to match the extension. (similar to talisman in case of talisman)

**Comment by jak-pan** [comment]
<img width="314" alt="Screenshot 2022-09-29 at 21 02 34" src="https://user-images.githubusercontent.com/3409250/193120100-c1d5c714-8b39-46d2-95ba-ac2a1b5ba8be.png">

like so https://github.com/galacticcouncil/Basilisk-ui/blob/9024cceb801b45d6ea8c367a2bcc5defc0c86997/src/pages/WalletPage/containers/WalletPage/ActiveAccount/ActiveAccount.tsx#L77-L102

**Comment by jak-pan** [comment]
Unfortunately we have ss58 but the idea of it is to guide user and show him the pairing between what he sees in the extension and what he sees later in our ui to avoid heavy confusion.

**Comment by dqbd** [comment]
> Ok I have been digging heavily and the option to get icon style vanished looks like as part of some upgrade... What we can do instead is that if we show default in-extension address underneath our ss58 we can use classic identicon instead of the one we use to match the extension. (similar to talisman in case of talisman)

That should be the case both for Talisman (which we had to reverse-engineer, maybe we could ask Talisman to opensource the logo instead?) and for Polkadot.js 🙂, where the extension avatars should match.  

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/1443449/193130600-5aefb08f-d4b8-4e94-94a6-333b634a6882.png">

<img width="947" alt="image" src="https://user-images.githubusercontent.com/1443449/193130731-3131959b-efa4-48a7-ae3a-c6bf5a635458.png">

As we're currently showing the in-extension address in the header as well, we're showing the extension avatars instead, does that make sense? @jak-pan 

<img width="224" alt="image" src="https://user-images.githubusercontent.com/1443449/193131179-e5feebd5-5649-44ca-a610-30aafbab1481.png">




> Unfortunately we have ss58 but the idea of it is to guide user and show him the pairing between what he sees in the extension and what he sees later in our ui to avoid heavy confusion.

Maybe as an idea, we could show both of the avatars next to each other in the header, to further highlight that it is the same account, as it is shown in the extension?

**Comment by jak-pan** [comment]
> Maybe as an idea, we could show both of the avatars next to each other in the header, to further highlight that it is the same account, as it is shown in the extension?

Might actually not be a good idea, will ask for designs
