### ISSUE TITLE
Toggle button for switching between All positions/my positions should be hidden

### ISSUE THREAD

**Issue by DuriSK** [galacticcouncil/Basilisk-mining-ui#99]
As user, when i access Pools&Farms page
I should not see toggle for switching between all positions/my positions
-----------------------------------------------------------------------
Currently we don't have users specific values fully calculated for header attributes "My balance locked in Farms" and "My balance locked in pools", so for first testing version, we dont want give user ability to switch between views.
We will give user way to switch it, when all values will be correct.

**Comment by dqbd** [comment]
Fixed by #102
